apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-nodeport
  namespace: {{COMPONENT_NAMESPACE}}
  labels:
    app.kubernetes.io/name: cockroachdb
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cockroachdb
  ports:
    - name: grpc
      port: 26257
      targetPort: grpc
      nodePort: 30012
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30013
