---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alibaba-log-controller
  namespace: {{ .Values.NameSpace }}
  labels:
    k8s-app: alibaba-log-controller
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: alibaba-log-controller
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: alibaba-log-controller
        version: {{ .Values.Version }}
    spec:
      serviceAccountName: alibaba-log-controller
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
      - name: alibaba-log-controller
{{ if eq .Values.Net "Internet" }}
        image: registry.{{ .Values.Region }}.aliyuncs.com/log-service/alibabacloud-log-controller:{{ .Values.Controller.Image.Tag }}
{{ else }}
        image: registry-vpc.{{ .Values.Region }}.aliyuncs.com/log-service/alibabacloud-log-controller:{{ .Values.Controller.Image.Tag }}
{{ end }} 
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - '-c'
              - ps -ef | grep -v grep | grep run-controller.sh
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1 
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - '-c'
              - ps -ef | grep -v grep | grep run-controller.sh
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1  
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        env:
          - name: "ALICLOUD_LOG_PROJECT"
            valueFrom:
              configMapKeyRef:
                name: alibaba-log-configuration
                key: log-project
          - name: "ALICLOUD_LOG_ENDPOINT"
            valueFrom:
              configMapKeyRef:
                name: alibaba-log-configuration
                key: log-endpoint
          - name: ALICLOUD_LOG_PRODUCT_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: alibaba-log-configuration
                key: log-endpoint
          - name: "ALICLOUD_LOG_MACHINE_GROUP"
            valueFrom:
              configMapKeyRef:
                name: alibaba-log-configuration
                key: log-machine-group
          - name: "ALICLOUD_DAEMONSET_EXTERNAL_USER_DEFINE_IDS"
            valueFrom:
              configMapKeyRef:
                name: alibaba-log-configuration
                key: daemonset.external-user-define-ids
          - name: "ALICLOUD_STATEFULSET_EXTERNAL_USER_DEFINE_IDS"
            valueFrom:
              configMapKeyRef:
                name: alibaba-log-configuration
                key: statefulset.external-user-define-ids
          - name: "ALICLOUD_LOGTAIL_USER_DEFINED_ID"
            value: "$(ALICLOUD_LOG_MACHINE_GROUP),$(ALICLOUD_DAEMONSET_EXTERNAL_USER_DEFINE_IDS)"
          - name: "ALICLOUD_STATEFULSET_LOGTAIL_USER_DEFINED_ID"
            value: "$(ALICLOUD_LOG_MACHINE_GROUP)-statefulset,$(ALICLOUD_STATEFULSET_EXTERNAL_USER_DEFINE_IDS)"
          - name: "ALICLOUD_SINGLETON_LOGTAIL_USER_DEFINED_ID"
            value: "$(ALICLOUD_LOG_MACHINE_GROUP)-singleton-logtail-statefulset-0"
          - name: "ALICLOUD_STATEFULSET_MACHINE_GROUP"
            value: "$(ALICLOUD_LOG_MACHINE_GROUP)-statefulset"
          - name: "ALICLOUD_SINGLETON_MACHINE_GROUP"
            value: "$(ALICLOUD_LOG_MACHINE_GROUP)-singleton"
          - name: "ALICLOUD_ACS_K8S_FLAG"
            value: "{{ .Values.SLS_ACK_CLUSTER }}"
          - name: "ALICLOUD_LOG_CONTROLLER_NS"
            value: {{ .Values.NameSpace }}
          - name: "ALICLOUD_LOGTAIL_SERVICE_SWITCH"
            value: "true"
          - name: "ALICLOUD_LOGTAIL_SERVICE_NS"
            value: {{ .Values.NameSpace }}
          - name: "ALICLOUD_LOGTAIL_SERVICE_SELECTOR"
            value: "logtail-statefulset"
          - name: "ALICLOUD_LOGTAIL_ENDPOINT"
            value: "http://logtail-statefulset.{{ .Values.NameSpace }}:18689/export/port"
{{ if eq .Values.SLS_ACK_CLUSTER false }}
          - name: "ALICLOUD_ACCESS_KEY_ID"
            valueFrom:
              configMapKeyRef:
                name: alibaba-log-configuration
                key: access-key-id
          - name: "ALICLOUD_ACCESS_KEY_SECRET"
            valueFrom:
              configMapKeyRef:
                name: alibaba-log-configuration
                key: access-key-secret
{{ end }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aliyunlogconfigs.log.alibabacloud.com
spec:
  conversion:
    strategy: None
  group: log.alibabacloud.com
  names:
    kind: AliyunLogConfig
    listKind: AliyunLogConfigList
    plural: aliyunlogconfigs
    singular: aliyunlogconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true

---
apiVersion: rbac.authorization.k8s.io/v1
# v2 to avoid conflict with old
kind: ClusterRoleBinding
metadata:
  name: alibaba-log-controller-{{ .Values.NameSpace }}
subjects:
- kind: ServiceAccount
  name: alibaba-log-controller
  namespace: {{ .Values.NameSpace }}
roleRef:
  kind: ClusterRole
  name: alibaba-log-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alibaba-log-controller
  labels:
    k8s-app: alibaba-log-controller
rules:
- apiGroups: ["log.alibabacloud.com"] # "" indicates the core API group
  resources:
  - aliyunlogconfigs
  verbs:
  - update
  - get
  - watch
  - list
  - create
- apiGroups: [""] # "" indicates the core API group
  resources:
  - configmaps
  verbs:
  - create
  - update
  - get
- apiGroups: [""] # "" indicates the core API group
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups: [""] # "" indicates the core API group
  resources:
  - services
  verbs:
  - create
  - update
  - delete
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alibaba-log-controller
  namespace: {{ .Values.NameSpace }}
  labels:
    k8s-app: alibaba-log-controller
---