apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: {{COMPONENT_NAMESPACE}}
data:
  nats.conf: |
    port: 4222
    http: 8222
    server_name: $POD_NAME
    authorization {
      token: $NATS_TOKEN
    }
    jetstream {
      store_dir: "/data/jetstream"
      max_mem_store: 1Gi
      max_file_store: 6Gi
    }
    cluster {
      name: hg
      port: 6222
      routes = [
{{NATS_ROUTES}}
      ]
    }
