apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: {{COMPONENT_NAMESPACE}}
  labels:
    app.kubernetes.io/name: nats
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: nats
  ports:
    - name: client
      port: 4222
      targetPort: client
    - name: cluster
      port: 6222
      targetPort: cluster
    - name: monitor
      port: 8222
      targetPort: monitor
---
apiVersion: v1
kind: Service
metadata:
  name: nats-public
  namespace: {{COMPONENT_NAMESPACE}}
  labels:
    app.kubernetes.io/name: nats
spec:
  selector:
    app.kubernetes.io/name: nats
  ports:
    - name: client
      port: 4222
      targetPort: client
    - name: monitor
      port: 8222
      targetPort: monitor
