apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: delete-pod-by-names
spec:
  experiments:
  - scope: pod
    target: pod
    action: delete
    desc: "delete pod by names"
    matchers:
    - name: names
      value:
      - "redis-slave-674d68586-86r2t"
      - "frontend-d89756ff7-hmm62"
    - name: namespace
      value:
      - "default"
