apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: node-disk-load-burn-read
spec:
  experiments:
  - scope: node
    target: disk
    action : "burn"
    desc: "increase disk burn by names"
    matchers:
    - name: names
      value:
      - "k8s-node2"
    - name: path
      value:
      - "/home"
    - name: size
      value:
      - "20"
    - name: timeout
      value:
      - "100"
    - name: read
      value:
      - "true"
