apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: {{KUBE_TOKEN}}
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: {{KUBE_ADVERTISE_ADDRESS}}
  bindPort: {{KUBE_BIND_PORT}}
nodeRegistration:
  criSocket: {{CRI_SOCKET_SOCK_FILE}}
  imagePullPolicy: {{KUBE_IMAGE_PULL_POLICY}}
  name: {{KUBE_NODE_NAME}}
  taints: null

---
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: {{KUBERNETES_PKI_PATH}}
clusterName: kubernetes
controlPlaneEndpoint: {{KUBE_ADVERTISE_ADDRESS}}:{{KUBE_BIND_PORT}}
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: {{KUBERNETES_ETCD}}
imageRepository: {{GLOBAL_IMAGE_REPOSITORY}}
kind: ClusterConfiguration
kubernetesVersion: {{KUBE_VERSION}}
networking:
  dnsDomain: cluster.local
  serviceSubnet: {{KUBE_SERVICE_SUBNET}}
  podSubnet: {{KUBE_POD_SUBNET}}
scheduler: {}
apiServer:
  timeoutForControlPlane: 4m0s

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
cgroupsPerQOS: true

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
