apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-{{VALKEY_NAME}}-config
  namespace: {{COMPONENT_NAMESPACE}}
data:
  valkey.conf: |
    appendonly yes
    protected-mode yes
    dir /data
    save 900 1
    save 300 10
    save 60 10000
