apiVersion: v1
kind: Service
metadata:
  name: valkey-{{VALKEY_NAME}}
  namespace: {{COMPONENT_NAMESPACE}}
  labels:
    app.kubernetes.io/name: valkey-{{VALKEY_NAME}}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: valkey-{{VALKEY_NAME}}
  ports:
    - name: redis
      port: 6379
      targetPort: redis
