apiVersion: v1
kind: Service
metadata:
  name: openobserve-nodeport
  namespace: monitoring
  labels:
    app.kubernetes.io/name: openobserve
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: openobserve
  ports:
    - name: http
      port: 5080
      targetPort: http
      nodePort: 30017
