apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: monitoring
  labels:
    app.kubernetes.io/name: openobserve
spec:
  selector:
    app.kubernetes.io/name: openobserve
  ports:
    - name: http
      port: 5080
      targetPort: http
    - name: grpc
      port: 5081
      targetPort: grpc
