apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: {{COMPONENT_NAMESPACE}}
  labels:
    app.kubernetes.io/name: clickhouse
spec:
  selector:
    app.kubernetes.io/name: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: native
      port: 9000
      targetPort: native
